1725203198920	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1725206568307	Sync.SyncScheduler	DEBUG	Woke from sleep.
1725206568308	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1725206568308	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1725206568308	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725206568481	Sync.Service	DEBUG	User-Agent: Firefox/129.0.2 (Linux x86_64) FxSync/1.131.0.20240820123043.desktop
1725206568481	Sync.Service	INFO	Starting sync at 2024-09-01 21:32:48 in browser session lmOE9UNwGi5l
1725206568481	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725206568483	Sync.Status	INFO	Resetting Status.
1725206568483	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1725206568483	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1725206568483	FirefoxAccounts	DEBUG	getOAuthToken enter
1725206568483	FirefoxAccounts	TRACE	getCachedToken returning cached token
1725206568483	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1725206568484	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1725206568484	Sync.SyncAuthManager	INFO	Getting sync key
1725206568484	FirefoxAccounts	DEBUG	getOAuthToken enter
1725206568484	FirefoxAccounts	TRACE	getCachedToken returning cached token
1725206568484	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1725206568484	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1725206568484	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1725206568484	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1725206568484	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1725206568486	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1725206568486	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1725206568487	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1725206568487	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1725206568487	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1725206568487	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1725206568487	FirefoxAccounts	TRACE	Getting command keys: https://identity.mozilla.com/cmd/open-uri
1725206568488	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1725206568488	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1725206568488	FirefoxAccounts	TRACE	Getting command keys: https://identity.mozilla.com/cmd/close-uri/v1
1725206568492	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/261848012/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725206568492	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1725206568492	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1725206568492	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725206568492	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1725206568492	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1725206568494	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
